"""initial postgres migration

Revision ID: e47b16570a19
Revises: 
Create Date: 2020-02-23 13:17:31.375261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47b16570a19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_name'), 'item', ['name'], unique=True)
    op.create_table('item_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locked_item_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locked_ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('item_rank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('item_list_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['item_list_id'], ['item_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_rank_item_id'), 'item_rank', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_rank_item_list_id'), 'item_rank', ['item_list_id'], unique=False)
    op.create_index(op.f('ix_item_rank_rank'), 'item_rank', ['rank'], unique=False)
    op.create_table('locked_item_rank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('locked_item_list_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['locked_item_list_id'], ['locked_item_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locked_item_rank_item_id'), 'locked_item_rank', ['item_id'], unique=False)
    op.create_index(op.f('ix_locked_item_rank_locked_item_list_id'), 'locked_item_rank', ['locked_item_list_id'], unique=False)
    op.create_index(op.f('ix_locked_item_rank_rank'), 'locked_item_rank', ['rank'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('item_list_locked', sa.Boolean(), nullable=True),
    sa.Column('item_list_id', sa.Integer(), nullable=True),
    sa.Column('locked_item_list_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_list_id'], ['item_list.id'], ),
    sa.ForeignKeyConstraint(['locked_item_list_id'], ['locked_item_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('item_rank_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_rank_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('old_item_id', sa.Integer(), nullable=True),
    sa.Column('new_item_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_rank_id'], ['item_rank.id'], ),
    sa.ForeignKeyConstraint(['new_item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['old_item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('item_rank_audit')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_locked_item_rank_rank'), table_name='locked_item_rank')
    op.drop_index(op.f('ix_locked_item_rank_locked_item_list_id'), table_name='locked_item_rank')
    op.drop_index(op.f('ix_locked_item_rank_item_id'), table_name='locked_item_rank')
    op.drop_table('locked_item_rank')
    op.drop_index(op.f('ix_item_rank_rank'), table_name='item_rank')
    op.drop_index(op.f('ix_item_rank_item_list_id'), table_name='item_rank')
    op.drop_index(op.f('ix_item_rank_item_id'), table_name='item_rank')
    op.drop_table('item_rank')
    op.drop_table('role')
    op.drop_table('locked_item_list')
    op.drop_table('item_list')
    op.drop_index(op.f('ix_item_name'), table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###
