"""Separating list_user and edit_user for ItemRankAudit

Revision ID: ff30bd3d92b4
Revises: e47b16570a19
Create Date: 2020-03-08 14:19:26.267336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff30bd3d92b4'
down_revision = 'e47b16570a19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_rank_audit', sa.Column('edit_user_id', sa.Integer(), nullable=True))
    op.add_column('item_rank_audit', sa.Column('list_user_id', sa.Integer(), nullable=True))
    op.drop_constraint('item_rank_audit_user_id_fkey', 'item_rank_audit', type_='foreignkey')
    op.create_foreign_key(None, 'item_rank_audit', 'user', ['edit_user_id'], ['id'])
    op.create_foreign_key(None, 'item_rank_audit', 'user', ['list_user_id'], ['id'])
    op.drop_column('item_rank_audit', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_rank_audit', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'item_rank_audit', type_='foreignkey')
    op.drop_constraint(None, 'item_rank_audit', type_='foreignkey')
    op.create_foreign_key('item_rank_audit_user_id_fkey', 'item_rank_audit', 'user', ['user_id'], ['id'])
    op.drop_column('item_rank_audit', 'list_user_id')
    op.drop_column('item_rank_audit', 'edit_user_id')
    # ### end Alembic commands ###
